config/routes.rb
Liberator::Application.routes.draw do
  resources :tags

  resources :authors

  resources :books do
    get :download, :on => :member, :to => 'books#download'
  end
  match '/books/search', :controller => 'books', :action => 'search'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :datum, :foreign_key => "book"
  has_one :comment, :foreign_key => "book"
  has_and_belongs_to_many :authors, :join_table => "books_authors_link", :foreign_key => "book", :association_foreign_key => "author"
  has_and_belongs_to_many :tags, :join_table => "books_tags_link", :foreign_key => "book", :association_foreign_key => "tag"

  @@library_basepath = "#{Rails.root}/public/Calibre Library"
  @@image_basepath = "/Calibre Library"

  def get_filepath (data_id)
    return "#{get_filedirectory}/#{get_filename(data_id)}"
  end

  def get_filedirectory
    return "#{get_library_basepath}/#{path}"
  end

  def get_library_basepath
    return @@library_basepath
  end

  def get_filename (data_id)
    return "#{datum[data_id].name}.#{get_extension(data_id).downcase}"
  end

  def get_extension (data_id)
    return "#{datum[data_id].format}"
  end

  def get_summary
    if (comment == nil)
      ""
    else
      comment.text
    end
      
  end

  def get_title
    title.strip.titleize
  end

  def get_author
    author_sort.titleize
  end

  def get_thumbnail
    "#{@@image_basepath}/#{path}/cover.jpg"
  end

  def is_has_cover
    if has_cover == 1 
      true
    else
      false
    end
  end

  def is_has_tags
    if (tags != nil && tags.size > 0)
      true
    else
      false
    end
  end

  def get_mime_type (data_id)
    return datum[data_id].get_mime_type
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # GET /books
  # GET /books.json
  def index
    puts "Search request: #{params[:search]}"

    if params[:search] != nil
      @books = Book.where("title LIKE '%#{params[:search]}%' OR author_sort LIKE '%#{params[:search]}%'").page(params[:page]).per(25)
    else
      @books = Book.page(params[:page]).per(25)
    end
    @recent_books = Book.find(:all, :order => "timestamp asc", :limit => 5)
    @books_to_read = Book.find(:all, :include=>:tags, :conditions => ['tags.name in (?)',['to-read']])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    # return send_file @book.get_filepath, :type => 'application/pdf', :filename => @book.get_filename
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  def download
    @book = Book.find(params[:id])
    data_id = Integer(params[:data_id])
    return send_file @book.get_filepath(data_id), :type => @book.get_mime_type(data_id), :filename => @book.get_filename(data_id)
  end

  # # GET /books/new
  # # GET /books/new.json
  # def new
  #   @book = Book.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @book }
  #   end
  # end

  # # GET /books/1/edit
  # def edit
  #   @book = Book.find(params[:id])
  # end

  # # POST /books
  # # POST /books.json
  # def create
  #   @book = Book.new(params[:book])

  #   respond_to do |format|
  #     if @book.save
  #       format.html { redirect_to @book, notice: 'Book was successfully created.' }
  #       format.json { render json: @book, status: :created, location: @book }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @book.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PUT /books/1
  # # PUT /books/1.json
  # def update
  #   @book = Book.find(params[:id])

  #   respond_to do |format|
  #     if @book.update_attributes(params[:book])
  #       format.html { redirect_to @book, notice: 'Book was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @book.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /books/1
  # # DELETE /books/1.json
  # def destroy
  #   @book = Book.find(params[:id])
  #   @book.destroy

  #   respond_to do |format|
  #     format.html { redirect_to books_url }
  #     format.json { head :no_content }
  #   end
  # end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr>
  <td>
    <% if book.is_has_cover %>
      <%= link_to image_tag(book.get_thumbnail, :width => 120), book_path(book) %>
    <% else %>
      <%= link_to image_tag('no_icon.gif', :width => 50), book_path(book) %>
    <% end %>
  </td>
  <td>
    <h4><%= book.get_title %></h4>
    <p class="muted">
      by
      <%= book.authors.collect{|author| author.name}.to_sentence %>
      Tags: 
      <%= book.tags.collect{|tag| tag.name}.to_sentence %>
    </p>
    <% data_id = 0 %>
    <% book.datum.each_with_index do |data, data_id| %>
      <%= link_to 'Get '+data.format, download_book_path(book, :data_id => data_id), :method => :get, :class => 'btn btn-mini btn-success' %>
    <% end %>
    <br />
    <%= truncate(book.get_summary, :length => 300, :separator => ' ') %>
  </td>
</tr>

app/views/books/_book_concise.html.erb
<tr>
  <td>
    <% if book.is_has_cover %>
      <%= link_to image_tag(book.get_thumbnail, :width => 50), book_path(book) %>
    <% else %>
      <%= link_to image_tag('no_icon.gif', :width => 50), book_path(book) %>
    <% end %>
  </td>
  <td>
    <h9><%= book.get_title %></h9>
    <p class="muted">
      by
      <%= book.authors.collect{|author| author.name}.to_sentence %>
      <% data_id = 0 %>
      <% book.datum.each_with_index do |data, data_id| %>
        <%= link_to 'Get '+data.format, download_book_path(book, :data_id => data_id), :method => :get, :class => 'btn btn-mini btn-success' %>
      <% end %>
    </p>
  </td>
<tr>

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :title, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sort, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :sort, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :timestamp, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :timestamp, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pubdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :pubdate, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :series_index, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :series_index, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author_sort, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :author_sort, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :isbn, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :isbn, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lccn, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :lccn, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :path, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :path, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :flags, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :flags, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :uuid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :uuid, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :has_cover, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :has_cover, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_modified, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :last_modified, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<% if @books.size <= 0 %>
  <h3>Couldn't find what you are looking for.<h3>Maybe try a different search.
<% else %>
  <%= paginate @books %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="100px"/>
        <th />
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <%= render 'book', :book => book %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @book.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sort) %>:</strong></dt>
  <dd><%= @book.sort %></dd>
  <dt><strong><%= model_class.human_attribute_name(:timestamp) %>:</strong></dt>
  <dd><%= @book.timestamp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pubdate) %>:</strong></dt>
  <dd><%= @book.pubdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:series_index) %>:</strong></dt>
  <dd><%= @book.series_index %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author_sort) %>:</strong></dt>
  <dd><%= @book.author_sort %></dd>
  <dt><strong><%= model_class.human_attribute_name(:isbn) %>:</strong></dt>
  <dd><%= @book.isbn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lccn) %>:</strong></dt>
  <dd><%= @book.lccn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:path) %>:</strong></dt>
  <dd><%= @book.path %></dd>
  <dt><strong><%= model_class.human_attribute_name(:flags) %>:</strong></dt>
  <dd><%= @book.flags %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uuid) %>:</strong></dt>
  <dd><%= @book.uuid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:has_cover) %>:</strong></dt>
  <dd><%= @book.has_cover %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_modified) %>:</strong></dt>
  <dd><%= @book.last_modified %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>