config/routes.rb
Liberator::Application.routes.draw do
  resources :tags

  resources :authors

  resources :books do
    get :download, :on => :member, :to => 'books#download'
  end
  match '/books/search', :controller => 'books', :action => 'search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caliberator - liberate your e-book library</title>
  <!-- [if lt  IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif] -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">CALIBRErator</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to 'Books', books_path() %></li>
          <li><%= link_to 'Authors', authors_path() %></li>
          <li><a href="#">Tags</a></li>
          <li><a href="#">Languages</a></li>
        </ul>
      </div>
      <%= form_tag 'books#index', :method => 'get', :class => "navbar-form pull-right" do %>
        <%= text_field_tag :search, params[:search], :class => "span2" %>
        <%= submit_tag "Search", :name => nil, :class => 'btn' %> 
      <% end %>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="row-fluid">
    <%if @books_to_read != nil and @books_to_read.size > 0 %>
      <div class="span2">
        <ul class="nav nav-list">
          <li class="nav-header"><%= @books_to_read.size %> Books to Read...</li>
        </ul>
        <table class="table table-striped">
          <thead>
            <th width="50" />
            <th />
          </thead>
          <tbody>
            <% @books_to_read.each do |book| %>
              <%= render 'book_concise', :book => book %>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
    <div class="span9"><%= yield %></div>
  </div>
</div>

</body>
</html>